### ISSUE TITLE
docker-compose : mongo not running

### ISSUE THREAD

**Issue by timconsidine** [colloqi/pisignage-server#200]
Used the linked docker-compose.yml with additions for traefik.
App page https://pisignage.domain.tld returns 404
docker logs show :
```
********************************************
*          MongoDB Process not running     *
********************************************

wait-for-it.sh: waiting 15 seconds for mongo:27017
nc: bad address 'mongo'
```

Docker-compose.yml is :
```
version: '3'
services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - $PWD/mongodb:/data/db
      - $PWD/mongodb_config:/data/configdb
  pisignage-server:
    image: pisignage/pisignage-server:latest
    restart: unless-stopped
    volumes:
      - $PWD/media:/media
      - $PWD/data:/data
    depends_on:
      - mongo
    labels:
      - traefik.docker.network=traefik
      - traefik.port=3000
      - "traefik.enable=true"
      - "traefik.http.routers.pisignage.rule=Host(`pisignage.domain.tld`)"
      - "traefik.http.routers.pisignage.entrypoints=websecure"
      - "traefik.http.routers.pisignage.tls.certresolver=letsencrypt"
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  mongodb:
  mongodb_config:
  media:
  data:
```

How do I get mongo started in the container ?
